name: 'Build'
description: 'Build the angular project for the specified stage'
inputs:
  bucket-name:
    description: 'The deploy bucket'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.bucket-name }}
